trigger:
- master

variables:
  MONO_REVISION: '2019-08'

jobs:
- job: Build_Mono
  timeoutInMinutes: 0
  pool:
   vmImage: 'windows-2019'
  steps:
  - script: |
      mkdir Binaries
      git clone --recurse-submodules --branch %MONO_REVISION% https://github.com/mono/mono.git
    displayName: 'Fetch mono repo'
  - task: BatchScript@1
    inputs:
      filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat'
      modifyEnvironment: True
  - script: |
      cd mono
      msbuild msvc\mono.sln /p:PlatformToolset=v142 /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:Platform=Win32 /p:Configuration=Release /p:MONO_BUILD_DIR_PREFIX="$(MSBuildProjectDirectory)/../Binaries/" /p:MONO_TARGET_GC=sgen  /restore
      msbuild msvc\mono.sln /p:PlatformToolset=v142 /p:WindowsTargetPlatformVersion=10.0.18362.0 /p:Platform=x64 /p:Configuration=Release /p:MONO_BUILD_DIR_PREFIX="$(MSBuildProjectDirectory)/../Binaries/" /p:MONO_TARGET_GC=sgen  /restore
      msbuild bcl.sln /p:Configuration=Release /p:Platform="net_4_x" /restore
    displayName: 'Build mono'
    continueOnError: true
    failOnStderr: false
  - powershell: |
      7z a mono.zip Binaries\*
    displayName: 'Copy Binaries'
  - publish: $(Build.SourcesDirectory)/mono.zip
    artifact: Mono Binaries
  
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'msmshazan Github PAT'
      repositoryName: 'msmshazan/monobuild'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'Release-$(MONO_REVISION)'
      title: 'Mono Binaries'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
      assets: '$(Build.SourcesDirectory)/mono.zip'
