trigger:
- master

variables:
  MONO_REVISION: '2020-02'

jobs:
- job: Build_Mono
  timeoutInMinutes: 0
  pool:
   vmImage: 'windows-2019'
  steps:
  - powershell: |
      choco install mono 2>&1>$null
      Invoke-WebRequest -Uri "https://cygwin.com/setup-x86_64.exe" -OutFile setup-x86_64.exe
      .\setup-x86_64.exe --local-package-dir D:\misc\cygwin\packages -B -P autoconf,automake,bison,gcc-core,gcc-g++,mingw64-i686-runtime,mingw64-i686-binutils,mingw64-i686-gcc-core,mingw64-i686-gcc-g++,mingw64-i686-pthreads,mingw64-i686-w32api,mingw64-x86_64-runtime,mingw64-x86_64-binutils,mingw64-x86_64-gcc-core,mingw64-x86_64-gcc-g++,mingw64-x86_64-pthreads,mingw64-x86_64-w32api,libtool,make,python,gettext-devel,gettext,intltool,libiconv,pkg-config,git,curl,wget,libxslt,bc,patch,cmake,perl,yasm,unzip
      Remove-Item setup-x86_64.exe
    displayName: 'Fetch Cygwin'
  - script: |
      mkdir Binaries
      git clone --recurse-submodules https://github.com/mono/mono.git
    displayName: 'Fetch mono repo'
  - task: BatchScript@1
    inputs:
      filename: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat'
      modifyEnvironment: True
  - bash: |
      export PREFIX=$(pwd)/Binaries
      export PATH='C:/Program Files/Mono/bin':$PATH
      cd mono
      ./autogen.sh --prefix=$PREFIX --host=i686-w64-mingw32--enable-msvc --disable-boehm
      make get-monolite-latest
      make -j4
      make install
      ./autogen.sh --prefix=$PREFIX --host=x86_64-w64-mingw32 --enable-msvc --disable-boehm
      make -j4
      make install    
    displayName: 'Build mono'
    continueOnError: true
    failOnStderr: false
  - powershell: |
      7z a mono.zip Binaries\*
    displayName: 'Copy Binaries'
  - publish: $(Build.SourcesDirectory)/mono.zip
    artifact: Mono Binaries
  
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'msmshazan Github PAT'
      repositoryName: 'msmshazan/monobuild'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'Release-$(MONO_REVISION)'
      title: 'Mono Binaries'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
      assets: '$(Build.SourcesDirectory)/mono.zip'
