trigger:
- master

variables:
  MONO_REVISION: '2019-08'

jobs:
- job: Build_Mono
  timeoutInMinutes: 0
  pool:
   vmImage: 'windows-2019'
  steps:
  - powershell: |
      New-Item -Name "Binaries" -ItemType "directory"
      git clone --branch $(MONO_REVISION) https://github.com/mono/mono.git
      cd mono
      git submodule update --recursive
    displayName: 'Fetch mono repo'

  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
      refreshenv
      cd mono
      msbuild msvc\mono.sln /p:Platform=x64 /p:Configuration=Release /p:MONO_BUILD_DIR_PREFIX="..\Binaries\" /p:MONO_TARGET_GC=sgen
      msbuild bcl.sln /p:Platform="net_4_x" /restore
      msbuild msvc\mono.sln /p:Platform=Win32 /p:Configuration=Release /p:MONO_BUILD_DIR_PREFIX="..\Binaries\" /p:MONO_TARGET_GC=sgen
      msbuild bcl.sln /p:Platform="net_4_x" /restore
    displayName: 'Build mono'
  - powershell: |
      7z a mono.zip Binaries\*
    displayName: 'Copy Binaries'
  - publish: $(Build.SourcesDirectory)/mono.zip
    artifact: Mono Binaries

  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'msmshazan Github PAT'
      repositoryName: 'msmshazan/anglebuild'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: 'Release-$(MONO_REVISION)'
      title: 'ANGLE Binaries'
      changeLogCompareToRelease: 'lastFullRelease'
      changeLogType: 'commitBased'
      assets: '$(Build.SourcesDirectory)/mono.zip'
